import type { Metadata } from "next";
import "@/styles/globals.css";

import { Plus_Jakarta_Sans, Poppins } from "next/font/google";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], // bisa sesuaikan
  display: "swap",
  variable: "--font-jakarta", // CSS variable (opsional)
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Vibloo",
  description: "Generated by create next app",
  icons: {
    icon: "/v.svg", // code untuk mengganti icon website
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakarta.variable} ${poppins.variable} bg-bg`}>{children}</body>
    </html>
  );
}
